### ISSUE TITLE
In appropriate Japanese translation

### ISSUE THREAD

**Issue by VigneshMitsume** [MicrosoftDocs/Viva#502] opened 2023-01-18 06:49 UTC
In this page, the word "Resilience" is translated as "回復" which is completely in appropriate word in the given document.
Hence requesting to change the word "回復" to "レジリエンス" which is more appropriate usage in terms of business.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 28297e84-3745-355c-9090-ac9238466343
* Version Independent ID: 28297e84-3745-355c-9090-ac9238466343
* Content: [Business resilience report](https://learn.microsoft.com/en-us/viva/insights/advanced/analyst/templates/business-resilience)
* Content Source: [Viva/insights/advanced/analyst/templates/business-resilience.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/Viva/insights/advanced/analyst/templates/business-resilience.md)
* Service: **viva**
* Sub-service: **viva-insights**
* GitHub Login: @lilyolason
* Microsoft Alias: **v-lilyolason**

**Comment by tiburd** [comment] 2023-01-23 16:06
Thank you for submitting this localization issue.

I submitted a translation bug: [260010](https://dev.azure.com/GlobalCollaborationService/Global%20Collaboration%20Service%20Project/_workitems/edit/260010)

I'm closing this issue because the Global Services team will handle it from here.

**Closed by tiburd** 2023-01-23 16:06 UTC
Labels: loc-bug

**Comment by tiburd** [comment] 2023-02-03 16:35
I received notification that the issue is resolved.
Thanks again for bringing it to our attention.
