### ISSUE TITLE
Inconsistent information on documentation

### ISSUE THREAD

**Issue by martinctc** [MicrosoftDocs/Viva#321] opened 2022-06-01 13:32 UTC
There appears to be inconsistent / contradictory information on the documentation. 

On one paragraph, this describes that Insights Administrators _will_ get an email after being assigned a role: 

> Within a few days after being assigned a Viva Insights role, these users will get an email about what product features are available based on their role and service plan.

Towards the bottom, the opposite is described:

> If you assigned the Microsoft Viva Insights (WpA transition) license to one or more people, they will also not receive an email notification. So you'll need to notify them as well. 

Please fix / clarify - thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b82335a2-a73c-440a-02fe-c8867c78a99f
* Version Independent ID: 9f52158f-f0cc-efb5-5177-73fef4d4a981
* Content: [Assign roles for Microsoft Viva Insights](https://docs.microsoft.com/en-us/viva/insights/setup/assign-user-roles)
* Content Source: [Viva/insights/Setup/assign-user-roles.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/Viva/insights/Setup/assign-user-roles.md)
* Service: **viva**
* Sub-service: **viva-insights**
* GitHub Login: @madehmer
* Microsoft Alias: **helayne**

**Comment by dariomws** [comment] 2022-07-22 11:31
Same as https://github.com/MicrosoftDocs/Viva/issues/322.

**Comment by get-itips** [comment] 2022-07-22 16:13
Closed as duplicate of https://github.com/MicrosoftDocs/Viva/issues/322

**Closed by get-itips** 2022-07-22 16:13 UTC
Labels: Microsoft submitter, doc-bug
